### ISSUE TITLE
Please Add Support for TFA-Dostmann AIRCO2NTROL Coach CO2 Monitor

### ISSUE THREAD

**Issue by buliwyf42** [JsBergbau/TFACO2AirCO2ntrol_CO2Meter#1]
Hello,

i bought a TFA-Dostmann AIRCO2NTROL Coach CO2 Monitor http://www.amazon.de/dp/B07R4XM9Z6
This uses the same API and Infos but das not encrypt the data. Therefore your script cannot handle it. 
For Office Weather there is already a Pull Request for the implementation. https://github.com/wreiner/officeweather/pull/2/files.
It would be great if you could add this.

Thanks. Danke

**Comment by JsBergbau** [comment]
Hi buliwyf42,

thanks for your help. I've implemented it. Give it a try and please report back how it works.

**Comment by buliwyf42** [comment]
Hi, this seems to work.
Only the Humidity does not work because the script uses 0x44 for Humidity and the Sensors uses 0x41 for Humidity.
This seems different. If i change this:
```
			 if 0x42 in values:
				 print ("T: %2.2f" % (values[0x42]/16.0-273.15))
			 if 0x41 in values:
				 print ("RH: %2.2f" % (values[0x41]/100.0))
			 print
```

Humidity works as well. 

Thanks for implementing my Request so far.

**Comment by JsBergbau** [comment]
Hi buliwyf42
Thanks for your feedback. I've updated. Check it out.

**Comment by buliwyf42** [comment]
Well done. Works like a charm. :) 

> pi@raspberrypi:~/TFACO2AirCO2ntrol_CO2Meter $ ./co2monitor.py /dev/hidraw0
RH: 24.75
RH: 24.75
CO2: 1265
RH: 24.75
CO2: 1265
T: 27.91
RH: 24.75
CO2: 1265
T: 27.91
RH: 24.75
CO2: 1265
T: 27.91
RH: 24.75
CO2: 1265
T: 27.91
RH: 24.75
CO2: 1265
T: 27.91
RH: 24.75
CO2: 1265
T: 27.91
RH: 24.75
CO2: 1265
T: 27.91
RH: 24.75


Thank you

**Comment by JsBergbau** [comment]
You're welcome.
